WindowManager:
    ScreenMenu:
        Menu:
    ScreenOptions:
        Options:
    ScreenEndlessGameSelection:
        Endless:
    ScreenSurvivalGameSelection:
        Survival:

<ScreenMenu>:
    name: "menu"

<Menu>:

<ScreenOptions>:
    name: "Options"

<Options>:

<ScreenEndlessGameSelection>:
    name: "Endless"

<ChooseDifficulty>:

<Endless>:

<ScreenSurvivalGameSelection>:
    name: "Survival"

<Survival>:
